Capstone Project
Alondra87/Capstone pull request #1
Opened 2022-05-18 17:05 UTC by Alondra87

This final project is based on an online website for a conference. Instead of a conference I created a website for a cultural event.
This link is for the demo of the project: https://www.loom.com/share/90bc35a9c40f489c83f69b6c9133919d

2022-05-19 19:59 UTC, Alondra87 commented
Changes made:
>For the mobile version:
I increased the length of the pop-up menu so it covers the page.
 >For the desktop version:
I added the top dark bar like it appears in the template with a section for social media links, logout and language links aligned to the right.
I aligned the logo and text as in the template.
I ensured that the footer on the mobile version has a white background and not a dark one.
I added a border-bottom for the link in program section like in the template.
I added the checked background image behind each speaker, like it is in the template.
I aligned the image and the text in the speaker’s section.
I included a line below every heading as temple.
I aligned images vertically in memories section.

2022-05-19 20:33 UTC, Ismailco requested changes
Hi @Alondra87,
Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![giphy](https://user-images.githubusercontent.com/25227022/169399289-510de072-42e7-419b-8c2c-da9344bdd430.gif)

## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-05-19 20:33 UTC, Ismailco commented on index.html
> +            <div class="hamburger">
- [ ] [Optional] The hamburger menu should be aligned to the left of the page, kindly change the menu from the right to the left

|Your design|CC design|
|--|--|
|![Screenshot_20220519_210854](https://user-images.githubusercontent.com/25227022/169397002-8784f988-308d-40ad-96b7-0ced37a0f51d.png)|![Screenshot_20220519_211705](https://user-images.githubusercontent.com/25227022/169397097-a7c76c26-5640-406e-abca-1b75b2678f13.png)|

2022-05-19 20:33 UTC, Ismailco commented on index.html
> +<section class="partners" id="sponsor">
- [ ] [Optional] The images in this section should be centered with no background or dark background, please consider making the changes so the design is as close to the provided one as possible

|Your design|CC design|
|---|---|
|![Screenshot_20220519_212441](https://user-images.githubusercontent.com/25227022/169398263-62a246a8-4ec6-47d8-966c-71c8540f5fe9.png)|![Screenshot_20220519_212123](https://user-images.githubusercontent.com/25227022/169398161-833c6b0e-d99f-457f-9051-bbc6be76cfa6.png)|

2022-05-19 20:33 UTC, Ismailco commented on index.html
> +            <div class="hamburger">
- [ ] [Optional] The nav links should align to the right of the navbar, please consider moving the links to the right and reducing some margin/padding

|Your design|CC design|
|---|---|
|![Screenshot_20220519_211814](https://user-images.githubusercontent.com/25227022/169398471-f85caf8f-1330-4908-ba2d-17965252e16e.png)|![Screenshot_20220519_211835](https://user-images.githubusercontent.com/25227022/169397631-ada4b8d2-d784-4b33-bafd-dae4a3c459aa.png)|

2022-05-20 17:05 UTC, Alondra87 commented
I made all the changes, thanks.

2022-05-20 17:28 UTC, vic778 approved these changes
Hi @Alondra87 l  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Charlie Brown](https://media.giphy.com/media/ZdO4NenDbsQNwUwKDB/giphy.gif)

## Highlights

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2022-05-20 18:55 UTC, merged